ALTER TABLE products
ADD COLUMN IF NOT EXISTS has_variations BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS variation_options JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS variation_skus JSONB DEFAULT '[]'::jsonb;
